apiVersion: v1
kind: Service
metadata:
  name: arc-listener-metrics
  namespace: {{ .Values.controllerNamespace }}
  labels:
    app.kubernetes.io/name: arc-listener-metrics
spec:
  selector:
    app.kubernetes.io/component: runner-scale-set-listener
    actions.github.com/scale-set-name: {{ .Values.runnerScaleSetName }}
    actions.github.com/scale-set-namespace: {{ .Values.runnerNamespace }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arc-listener
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: github-arc-runners
spec:
  namespaceSelector:
    matchNames: [{{ .Values.controllerNamespace }}]
  selector:
    matchLabels:
      app.kubernetes.io/name: arc-listener-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.scrapeInterval }}
