defaultRules:
  create: true

grafana:
  replicas: 1
  persistence:
    enabled: false
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 256Mi

prometheus:
  prometheusSpec:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
      group_by: ["alertname", "namespace", "workload"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: "null"
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
