apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: golden-path-recording-rules
  labels:
    app.kubernetes.io/part-of: observability-golden-path
    release: kube-prometheus-stack
spec:
  groups:
    - name: golden-path.recording
      rules:
        - record: golden_path:workload_readiness_ratio
          expr: |
            sum by (namespace, workload) (kube_pod_status_ready{condition="true"} * on(namespace,pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel)
            /
            sum by (namespace, workload) (kube_pod_info * on(namespace,pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel)
        - record: golden_path:namespace_cpu_usage_ratio
          expr: |
            sum by (namespace) (rate(container_cpu_usage_seconds_total{container!="",image!=""}[5m]))
            /
            sum by (namespace) (kube_pod_container_resource_requests{resource="cpu"})
        - record: golden_path:namespace_memory_usage_ratio
          expr: |
            sum by (namespace) (container_memory_working_set_bytes{container!="",image!=""})
            /
            sum by (namespace) (kube_pod_container_resource_requests{resource="memory"})
        - record: golden_path:pod_restart_rate
          expr: |
            sum by (namespace, pod) (rate(kube_pod_container_status_restarts_total[15m]))

