{
 "title": "Logs",
 "tags": [ "golden-path" ],
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(cluster)" },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "workload", "query": "label_values(workload)" },
   { "name": "pod", "query": "label_values(pod)" },
   { "name": "container", "query": "label_values(container)" }
  ]
 },
 "panels": [
  {
   "title": "Are error and warning logs increasing?",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate({namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"} |~ \"(?i)error|warn\" [5m]))"
    }
   ]
  },
  {
   "title": "Which namespaces and workloads produce logs?",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, workload) (rate({namespace=~\"$namespace\",workload=~\"$workload\"}[5m]))"
    }
   ]
  },
  {
   "title": "Which Pods are noisy?",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, sum by (namespace,pod) (rate({namespace=~\"$namespace\",pod=~\"$pod\"}[5m])))"
    }
   ]
  },
  {
   "title": "What Kubernetes warning events happened?",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} |~ \"Warning\""
    }
   ]
  },
  {
   "title": "Which Pods failed scheduling?",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} |~ \"FailedScheduling\""
    }
   ]
  },
  {
   "title": "Which containers are in BackOff or ImagePullBackOff?",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} |~ \"BackOff|ImagePullBackOff\""
    }
   ]
  },
  {
   "title": "Which volumes failed to mount?",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} |~ \"FailedMount\""
    }
   ]
  }
 ]
}