---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  labels:
    app.kubernetes.io/managed-by: k8s-namespace-onboarding
    platform.example.com/team: catalog
    platform.example.com/environment: development
    platform.example.com/owner: catalog-team
    platform.example.com/cost-center: engineering
  namespace: catalog-development
automountServiceAccountToken: false
