---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-developer
  labels:
    app.kubernetes.io/managed-by: k8s-namespace-onboarding
    platform.example.com/team: catalog
    platform.example.com/environment: development
  namespace: catalog-development
automountServiceAccountToken: false
