---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  labels:
    app.kubernetes.io/managed-by: k8s-namespace-onboarding
    platform.example.com/team: catalog
    platform.example.com/environment: development
  namespace: catalog-development
spec:
  hard:
    requests.cpu: '2'
    requests.memory: 4Gi
    limits.cpu: '2'
    limits.memory: 4Gi
    pods: '10'
