fullnameOverride: kube-prometheus-stack

defaultRules:
  create: true
grafana:
  defaultDashboardsEnabled: false
  defaultDatasourceUid: prometheus
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      searchNamespace: observability
      provider:
        folder: Golden Path
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
      isDefault: false
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: local
      environment: local
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
      group_by: ["alertname", "namespace", "workload"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: "null"
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
kube-state-metrics:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
