fullnameOverride: kube-prometheus-stack

defaultRules:
  create: true
grafana:
  defaultDashboardsEnabled: false
  defaultDatasourceUid: prometheus
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      searchNamespace: observability
      provider:
        folder: Golden Path
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
      isDefault: false
prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
kube-state-metrics:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
