fullnameOverride: kube-prometheus-stack

defaultRules:
  create: true
grafana:
  defaultDashboardsEnabled: false
  replicas: 2
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: Golden Path
      searchNamespace: observability
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
      isDefault: false
  podDisruptionBudget:
    minAvailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
prometheus:
  prometheusSpec:
    replicas: 2
    retention: 15d
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 4Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
    podAntiAffinity: soft
alertmanager:
  alertmanagerSpec:
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
    podAntiAffinity: soft
kube-state-metrics:
  replicas: 2
  podDisruptionBudget:
    minAvailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
